use_frameworks!

platform :ios, '9.0'

target 'JFPopup_Example' do
  pod 'JFPopup', :path => '../'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
             end
        end
      end
    end

  target 'JFPopup_Tests' do
    inherit! :search_paths

    
  end
end
